name: push dev brach to https://dev.kj.schniebs.com/
on:  
  push:
    branches:
      - dev
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'dev'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add mainp ssh://root@c1rrzs003p.schniebs.com:69/root/git/kjs-dev.git
        git push mainp dev
